### ISSUE TITLE
Proposal: Add link to gitter room in top nav

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda.github.io#100]
^^^ any interest in this?

**Comment by davidchambers** [comment]
Works for me. :)

**Comment by CrossEye** [comment]
Yup

**Comment by buzzdecafe** [comment]
ok, maybe someday soon

**Comment by MattMS** [comment]
Instead of simply having a link to Gitter, what about using [Gitter Sidecar](https://sidecar.gitter.im/) to embed the chat on the site?

It includes a button in the top-right corner to pop the chat out into a proper window.

**Comment by buzzdecafe** [comment]
> Instead of simply having a link to Gitter, what about using Gitter Sidecar to embed the chat on the site?

@MattMS that sounds good to me! I did not even know about "Gitter Sidecar"

**Comment by MattMS** [comment]
This seems to be fixed.

**Comment by buzzdecafe** [comment]
thanks
