### ISSUE TITLE
Consider use of js.org for hosting

### ISSUE THREAD

**Issue by MattMS** [ramda/ramda.github.io#101]
I've noticed a few projects using [js.org](https://js.org/) for hosting documentation.
Is there any interest in setting up ramda.js.org?

The [DNS page](https://dns.js.org/) and [GitHub repo](https://github.com/js-org/dns.js.org/) have instructions on how to set it up.
From my brief look, it just involves [adding an entry to a file in their repo](https://github.com/js-org/dns.js.org/blob/master/cnames_active.js).

Maybe this could be used for the manual?

**Comment by davidchambers** [comment]
Are you suggesting that we move the website from [ramdajs.com][1] to ramda.js.org?


[1]: http://ramdajs.com/

**Comment by MattMS** [comment]
That's one option, or a redirect from ramda.js.org to ramdajs.com, or maybe the manual hosted on ramda.js.org and the API docs on the other (not big on that idea though).

I just noticed the service and thought I'd throw it out there to get thoughts on it.

**Comment by davidchambers** [comment]
> I just noticed the service and thought I'd throw it out there to get thoughts on it.

It's a very cool service. We use it for [Sanctuary][1]. I recently discovered that it even supports HTTPS.

I don't see a reason to have two Ramda websites (even if they were to have different content).

The question is then whether the new domain name is an improvement on the existing one. I don't have a strong opinion on this matter. If we prefer the current name I don't see any reason to have a `ramda.js.org -> ramdajs.com` redirect. If we prefer the new name we'd clearly want to have a `ramdajs.com -> ramda.js.org` redirect in place.

I suggest sticking with the current domain name unless there's significant support for a switch.


[1]: https://sanctuary.js.org/

**Comment by CrossEye** [comment]
I agree with David.  This might have been a good idea when we were starting out.  But a domain name is cheap, and so far GitHub has been a fine host.
