### ISSUE TITLE
REPL doesn't respect `code` query parameter anymore

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda.github.io#102]
@kujon observed:

>Refreshing the page clears it.
>
>Chrome 52.0.2743.116 (64-bit)
>OS X 10.11.6
>
>@ codemirror.min.js:1 Uncaught TypeError: Cannot read property 'split' of undefinedH.splitLines
>@ codemirror.min.js:1splitLines
>@ codemirror.min.js:1(anonymous function)
>@ codemirror.min.js:1(anonymous function)
>@ codemirror.min.js:1(anonymous function)
>@ codemirror.min.js:14../googl
>@ bundle.js:251s
>@ bundle.js:1e
>@ bundle.js:1(anonymous function)
>@ bundle.js:1

**Comment by buzzdecafe** [comment]
this working fine in chrome 49 and firefox 50.0a2. is this a chrome52-specific problem?

**Comment by kujon** [comment]
`v` parameter seems to break it: http://ramdajs.com/repl/?v=0.22.1#?code=var%20a%20%3D%201%3B

**Comment by buzzdecafe** [comment]
yup. i wonder how long this has been broken

**Comment by buzzdecafe** [comment]
In ./docs/index.html.handlebars:

```html
<li><a href="/repl?v={{version}}">Try Ramda</a></li>
```

we used to have a snippet of code that would go and fetch the relevant version. That code has disappeared; I think the simplest thing to do is damn the old versions and only support the latest.

**Comment by fix-fix** [comment]
I opened PR to hopefully fix this #103

**Comment by CrossEye** [comment]
Thanks, @fix-fix!
