### ISSUE TITLE
Remove manual from version folders

### ISSUE THREAD

**Issue by MattMS** [ramda/ramda.github.io#107]
Considering the manual is not based on the version of Ramda, should it be removed from each of the version folders?

I'm also thinking that since it hasn't been linked from pages yet that it could be removed without breaking links.

Just to be clear, I'm not talking about removing the `manual` folder from the root of the repo.

**Comment by buzzdecafe** [comment]
> Considering the manual is not based on the version of Ramda, should it be removed from each of the version folders?

yup, excellent observation

**Comment by buzzdecafe** [comment]
i would :heart: a PR on this if you have the bandwidth
