### ISSUE TITLE
Add category filter to docs

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda.github.io#11]
copied from https://github.com/ramda/ramda/issues/713

"I think we should go with a dropdown and see what people think of that." -- @saikobee

**Comment by MattMS** [comment]
This seems complete?

I clicked on a category tag and it does a search based on the category name.

**Comment by CrossEye** [comment]
Yes, you're right.  We're bad enough about issues on the main repo.  Here they could languish forever.

**Comment by MattMS** [comment]
:smile: Happy to help bump one off the list.
