### ISSUE TITLE
Remove redirect from home page

### ISSUE THREAD

**Issue by MattMS** [ramda/ramda.github.io#117]
This might be controversial, but I'll give my reasoning for removing the home page redirect:

- You can bookmark a link that will always show the latest version.

- It makes building `index.html` easier (don't have to build into a version folder).

The latter idea was actually merged in #93, but that doesn't mean it can't be updated if this idea is not acceptable.

**Comment by buzzdecafe** [comment]
i'm not sure exactly what you are recommending. remove the redirect and replace it with what? Would the version folders no longer have index files?

**Comment by MattMS** [comment]
`/index.html` would match the `index.html` of the latest Ramda version.

So you could do `cp index.html <latest version>/index.html` after the page is built.

**Comment by buzzdecafe** [comment]
sounds fine to me.
