### ISSUE TITLE
docs generated? Or made by hand?

### ISSUE THREAD

**Issue by trusktr** [ramda/ramda.github.io#12]
If generated, what do you use?

**Comment by CrossEye** [comment]
We use JSDoc to generate them from the (generated) `ramda.js` file.

The template is our own, although it has some ancient roots in [the jaguar template][jt].

We generate them from a build script that you can run as `npm run docs`, but that immediately delegates to `grunt docs` for the bulk of the work.  You can see the configuration in the Gruntfile.  I no longer have a Windows machine to test on, so I would not be surprised to find that it only works in *nix environments.

  [jt]: https://github.com/davidshimjs/jaguarjs-jsdoc

**Comment by trusktr** [comment]
The docs are nice! Thanks!

**Comment by trusktr** [comment]
@CrossEye Where is the `docs` script? I don't see it here or in ramda/ramda.

**Comment by buzzdecafe** [comment]
in package.json:

```
 "scripts": {
    "clean": "rimraf tmp && rimraf out",
    "predocs": "npm run clean && npm run fetch",
    "docs": "grunt docs",
    "postdocs": "scripts/deploy",
    "fetch": "scripts/fetch",
    "postfetch": "scripts/prepFiles"
  },
```

`npm run docs` fetches the latest release and builds the docs.

**Comment by trusktr** [comment]
Oh, there's *two* `scripts` fields in package.js. I've never seen that before. I stopped looking after I saw the first one:

```js
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  ...
  "scripts": {
    "clean": "rimraf tmp && rimraf out",
    "predocs": "npm run clean && npm run fetch",
    "docs": "grunt docs",
    "postdocs": "scripts/deploy",
    "fetch": "scripts/fetch",
    "postfetch": "scripts/prepFiles"
  },
```

**Comment by davidchambers** [comment]
Yikes! That's an error. We should definitely remove the first occurrence.

**Comment by buzzdecafe** [comment]
i think that's on me.

**Comment by trusktr** [comment]
Hehe. Interesting that it worked.

**Comment by buzzdecafe** [comment]
https://github.com/ramda/ramda.github.io/commit/70e8c9a21ed2d68e676b964062b29923b6ca7958

**Comment by davidchambers** [comment]
:thumbsup:
