### ISSUE TITLE
Tapping status bar on docs page doesn’t scroll to top (iOS)

### ISSUE THREAD

**Issue by stevenbenisek** [ramda/ramda.github.io#123]

**Comment by stevenbenisek** [comment]
After the fix: scrolling down a bit and then tapping the status bar scrolls the page up

![ramdajs-fix-3](https://cloud.githubusercontent.com/assets/920729/18645766/cb68e7d8-7eae-11e6-88c3-0e7711dc4f72.gif)

**Comment by buzzdecafe** [comment]
this stuff all looks great -- I've been a bit down with a cold, just coming around now. I'll try and get to your PRs tonight/tomorrow. Thanks
