### ISSUE TITLE
No momentum scrolling `.docs-page main` and  `.sidebar .toc` (iOS)

### ISSUE THREAD

**Issue by stevenbenisek** [ramda/ramda.github.io#124]

**Comment by stevenbenisek** [comment]
![ramdajs-bug-2](https://cloud.githubusercontent.com/assets/920729/18645518/c8a9bf82-7ead-11e6-9136-cf51217ba749.gif)

![ramdajs-bug-4](https://cloud.githubusercontent.com/assets/920729/18645525/cfab1678-7ead-11e6-8030-6dafe9757f74.gif)

**Comment by stevenbenisek** [comment]
After: 

![ramdajs-fix-2](https://cloud.githubusercontent.com/assets/920729/18645810/038487d0-7eaf-11e6-9edc-4f3ca761a8a3.gif)

![ramdajs-fix-4](https://cloud.githubusercontent.com/assets/920729/18645821/0dfe9638-7eaf-11e6-8697-4d0d261b7631.gif)

**Comment by buzzdecafe** [comment]
closed by #126
