### ISSUE TITLE
Add Gitter room for this repo (docs/website)

### ISSUE THREAD

**Issue by MattMS** [ramda/ramda.github.io#135]
Would anyone be interested in a Gitter room for this repo?

I'm thinking it could be useful to separate docs/website chat from general chat.

**Comment by buzzdecafe** [comment]
if you think it would be useful, then sure. i am not on gitter very much myself.

**Comment by MattMS** [comment]
Not as useful if it's only me.

**Comment by buzzdecafe** [comment]
i guarantee i do not speak for everyone else :smile:

adding a gitter room costs nothing, so it couldn't hurt. You could always ping me individually on gitter as well; i would certainly respond to that (although maybe not super timely)

**Comment by craigdallimore** [comment]
Sounds good to me!

**Comment by MattMS** [comment]
I tried to add one but it wouldn't let me so I'm assuming only organisation members can do that.

**Comment by buzzdecafe** [comment]
https://gitter.im/ramda/ramda.github.io
