### ISSUE TITLE
Website REPL prepends code= to documentation examples

### ISSUE THREAD

**Issue by Joe-Withey** [ramda/ramda.github.io#144]
When going to the REPL from a 'Try in REPL link' we get the example code prepended with a `code=`

**Comment by buzzdecafe** [comment]
yup, this is not good. not sure if it's better to change the producer: https://github.com/ramda/ramda.github.io/blob/master/docs/main.js#L109
or the consumer, i.e. the REPL?

**Comment by Joe-Withey** [comment]
https://github.com/ramda/ramda.github.io/blob/master/repl/index.html#L90

`initialValue: URI.decode(window.location.hash).substring(7)`

for a quick and dirty fix

**Comment by MattMS** [comment]
I don't know if any changes to the REPL at the moment would be quick.

It would be simpler if the REPL used the entire URL hash value rather than dropping the first character.
But I'm not sure if having `?` at the start has some special significance.

**Comment by buzzdecafe** [comment]
the "?" bugs me as well.
