### ISSUE TITLE
Translate Ramda docoment into Chinese?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda.github.io#147]
As [discussed](https://github.com/ramda/ramda/issues/1951) before, I want to translate Ramda Api docoment into Simple Chinese. But there are some problems: 1. how to integrate the translation article into exited website; 2. how to keep the translation up to the latest library version.

**Comment by CrossEye** [comment]
https://github.com/ramda/ramda/issues/1951 suggested a translation of the documentation into Chinese.  I think this would be a great idea, and of course, we shouldn't be limited to just Chinese, but to whatever languages we had the volunteers to support.

There are technical issues of course, but also some non-technical ones:

  * How many volunteers do we need for a particular language?  Ramda isn't moving as quickly as it once did, but it's certainly not a static target, and releases tend to happen fairly quickly.  Even if we got ourselves more organized about that, we would need to know that all new and changed functions were properly translated.  

  * We should probably also translate the release notes, if possible.  Do we also try to do the home page and the Wiki pages?

  * Do we seek out volunteers for likely languages, trying to cover some large segment of the developer community?  Or do we simply wait for volunteers to appear to begin including a new language?

  * Do we allow a lag between when a version is published with up-to-date English documentation and when the translations are published?  Or do we ensure that all translations are completed before publishing a version?

**Or do we skip all this** and not worry about such details given that we have at the moment a single volunteer for a single language?  Should we just work out the technical kinks and assume the rest will be resolved when the need arises?


A very brief start at a technical solution
------------------------------------------

If we separate the JSDoc tags from the code, then we could easily support multiple versions.  I'm imagining something like:

**`src/filter.js`**:
```js
var _curry2 = require('./internal/_curry2');
var _dispatchable = require('./internal/_dispatchable');
var _filter = require('./internal/_filter');
var _isObject = require('./internal/_isObject');
var _reduce = require('./internal/_reduce');
var _xfilter = require('./internal/_xfilter');
var keys = require('./keys');


/** @sig Filterable f => (a -> Boolean) -> f a -> f a */

module.exports = _curry2(_dispatchable('filter', _xfilter, function(pred, filterable) {
  return (
    _isObject(filterable) ?
      _reduce(function(acc, key) {
        if (pred(filterable[key])) {
          acc[key] = filterable[key];
        }
        return acc;
      }, {}, keys(filterable)) :
    // else
      _filter(pred, filterable)
  );
}));
```

**`api/filter.api`**:
```js
/**
 * Takes a predicate and a "filterable", and returns a new filterable of the
 * same type containing the members of the given filterable which satisfy the
 * given predicate.
 *
 * Dispatches to the `filter` method of the second argument, if present.
 *
 * Acts as a transducer if a transformer is given in list position.
 *
 * @category List
 * @param {Function} pred
 * @param {Array} filterable
 * @return {Array}
 * @see R.reject, R.transduce, R.addIndex
 * @example
 *
 *      var isEven = n => n % 2 === 0;
 *      R.filter(isEven, [1, 2, 3, 4]); //=> [2, 4]
 *      R.filter(isEven, {a: 1, b: 2, c: 3, d: 4}); //=> {b: 2, d: 4}
 */
```

**`api/langs/zh/filter.api`**  (and please forgive the surely awful machine translation):
```js
/**
 * 需要一个谓语和一个“过滤”，并返回一个包含给定的过滤满足给定谓词的成员相同类型的新筛选
 *
 * 分派给第二个参数，如果存在`filter`方法。
 *
 * 如果变压器在列表中的位置给出充当传感器。
 *
 * @category 名单
 * @param {功能} pred
 * @param {排列} filterable
 * @return {排列}
 * @see R.reject, R.transduce, R.addIndex
 * @example
 *
 *      var Shènzhì = n => n % 2 === 0;
 *      R.filter(Shènzhì, [1, 2, 3, 4]); //=> [2, 4]
 *      R.filter(Shènzhì, {a: 1, b: 2, c: 3, d: 4}); //=> {b: 2, d: 4}
 */
```

(Or perhaps we don't put the English version at the root, but only in `api/langs/en`.  That's just a detail.)

Then at build time, for each language, we marry these docs with the functions and run JSDoc, generating a langauge-specific API documentation folder.  Obviously there would be work to do on the documentation template to allow the user to switch languages as well.

Does this sound as though it would work?  Does it sound like too much effort?  What do people think?

**Comment by CrossEye** [comment]
@adispring: If you'd be willing to write a proper translation for the `filter` function above, I'd love to use that instead of the Google Translate one I have there.

**Comment by adispring** [comment]
>@adispring: If you'd be willing to write a proper translation for the filter function above, I'd love to use that instead of the Google Translate one I have there.

This is the optimized Chinese translation.

```js
/**
 * 传入一个谓词和一个“过滤容器”，返回一个同类型新的过滤容器，其中包含满足谓词条件的过滤出来的元素。
 *
 * 如果存在`filter`方法。将其分派给第二个参数对应的`filter`方法，
 *
 * 如果在列出的位置中包含transfomer，则充当 transducer使用。
 *
 * @category 参数项
 * @param {Function} pred
 * @param {Array} filterable
 * @return {Array}
 * @see R.reject, R.transduce, R.addIndex
 * @example
 *
 *      var isEven = n => n % 2 === 0;
 *      R.filter(isEven, [1, 2, 3, 4]); //=> [2, 4]
 *      R.filter(isEven, {a: 1, b: 2, c: 3, d: 4}); //=> {b: 2, d: 4}
 */
```

**Comment by CrossEye** [comment]
> This is the optimized Chinese translation.

Thank you.

**Comment by MattMS** [comment]
I like the idea of only resolving the non-technical issues when they get raised again.

Would multi-language support change the structure of this repo/site?
Like everything would move under a language prefix: `/en/doc/`.

It seems there has been some [discussion in the JSDoc repo on i18n](https://github.com/jsdoc3/jsdoc/issues/1127).
The [jsdoc-i18n-plugin](https://github.com/villadora/jsdoc-i18n-plugin) was mentioned as useful.

It would also be nice to have a tool to validate the JSDoc versions to make sure they get fully updated.
A quick search gave me [jsdoced.js](https://github.com/jeromeetienne/jsdoced.js), but I'm not sure how far that project has progressed.

**Comment by CrossEye** [comment]
While I'm not a huge fan of our current huge JSDoc tag blocks in each file, it does seem as if we could do this relatively easily.  We'd have to internationalize the template too.  And it would be nice to use a message format to do so.  The trouble is that I don't find this very interesting work.  I don't know if there is someone who does.  I'm guessing that once the infrastructure is set up, it's still a reasonable, but not horrendous,  amount of work to convert all the docs to a given language, but that would be the lookout of any volunteers we have for that work.

**Comment by adispring** [comment]
I've created an organization [ramdacn](https://github.com/ramdacn)  on github, and invite some of my colleagues as volunteers. we will divide the work of translation by api category. If one api category is still too large, it will be divided again.

All of us have used ramda about half a year.

**Comment by tycho01** [comment]
Hey. I hadn't seen this issue yet earlier, but I've been having my Chinese employees use Ramda along with myself, but one had trouble with the English documentation, so I'd decided to go the first small step in getting a Chinese translation as well (if with focus on the functions common in my personal usage). As it stood it didn't appear there was current built-in support for i18n, so for now I'd gone the lazy way of using DOM selectors to extract/replace. If anyone's interested, my live version can be found [here](https://rawgit.com/tycho01/ramda.github.io/master/0.22.1/docs/), the current translation source [here](https://docs.google.com/spreadsheets/d/1XVuf1wbTuqoHCscsO7D2cW4ZnTy0zr12ohzAN8DRhf4/edit#gid=433928751). I'd gladly have this integrated with your efforts, @adispring.
