### ISSUE TITLE
REPL is down

### ISSUE THREAD

**Issue by Joe-Withey** [ramda/ramda.github.io#156]
Hey guys the REPL is experiencing an issue making it unusable. The output reads `Error: Failed to load http://wzrd.in/standalone/sanctuary@latest`

**Comment by buzzdecafe** [comment]
need to get in there and look, but S & RF failing to load should not kill the REPL. There may be a deeper problem here.

**Comment by buzzdecafe** [comment]
#157

**Comment by MattMS** [comment]
Is this issue staying open until Sanctuary and Ramda fantasy-land are back in the REPL?

**Comment by buzzdecafe** [comment]
yes
