### ISSUE TITLE
The Chinese translation have finished, and published.

### ISSUE THREAD

**Issue by adispring** [ramda/ramda.github.io#171]
we have just finished the translation of ramda api document, and published it with a new website: http://ramda.cn/.

we forked the ramda/ramda & ramda/ramda.github.io, and translate just on the forked repo: https://github.com/ramdacn/ramda/tree/coding-pages/src & https://github.com/ramdacn/ramda.github.io/blob/coding-pages/docs/index.html

But we want to separate the translate into a single directory, and write some scripts to translate the future ramda version automatically. Only translate the change part when ramda tag update, then run script to produce the new Chinese version of ramda. we are thinking how to do that.

**Comment by kedashoe** [comment]
Very cool! Would you like to submit a PR to link to it from ramdajs.com?

**Comment by adispring** [comment]
Since ramdajs.com's page is build automatically, how can I add a link to it? And add to which page, home page or document page ? @kedashoe

**Comment by kedashoe** [comment]
I was hoping you would know ;)

I think the home page is just the README in the ramda/ramda repo, right? Maybe add a new section after "Documentation" called "Translations" and throw a link to it in there?

**Comment by adispring** [comment]
Ok, I'll think about it :)

**Comment by buzzdecafe** [comment]
Quickest might be to make a PR vs. main ramda repo README; add a link in the documentation section. At least that will get something up there, we can try to raise the profile later

**Comment by MattMS** [comment]
This is very cool. 😄 

@adispring if you are unsure of what to put in the PR, just give me the text you would like updated in the README and I'll make up the PR and build the pages for you.

**Comment by adispring** [comment]
@MattMS The link has been added to ramda's README.md: https://github.com/ramda/ramda/pull/2147

**Comment by MattMS** [comment]
Great to hear, although now I've realised that getting that to the home page may take longer than I first anticipated.

Currently the home page of the site is built from the README in the latest published version of Ramda on npm.
If we were to follow current practices, then we would need to wait until a new version of Ramda is published before the changes can appear the site.

#142 is tracking an idea for updating the home page to not be dependent on the README, which would make adding changes like this easier.
As an aside, please add any comments to that issue, I'd love to see some other opinions.

A quicker alternative may be adding the translations above or below the README on the home page. (Any preferences? I think above.)
Maybe we could do this as some translated text saying "View in Chinese" or something like that?

**Comment by adispring** [comment]
@MattMS , we can add a dropdown switch button on the top right of website, like webpack doc's page: https://webpack.js.org/

**Comment by MattMS** [comment]
Nice idea for the drop-down.
I'm a bit hesitant in using flags to represent languages as I have heard there are quite a few nations that have multiple languages and it can become confusing.

At the moment, since we only have English and Chinese as translations, I think we could promote Chinese from English in a more prominent way, such as simply having some text to direct to Chinese or whatever you think is the most visible.

That said, these are my personal opinions and I would prefer to get some confirmation from core Ramda members to see how they would like this presented before a PR is crafted.

**Comment by kedashoe** [comment]
> nations that have multiple languages and it can become confusing.

makes sense to me, I think a drop down with the english and native text is a good way to go
