### ISSUE TITLE
REPL share button returns `undefined`

### ISSUE THREAD

**Issue by jlengstorf** [ramda/ramda.github.io#173]
On the REPL, clicking the share button returns `undefined`. It looks like the Google's URL shortener is returning `400`.

<img width="1440" alt="repl-share-error" src="https://cloud.githubusercontent.com/assets/163561/25998635/8deab0f2-36e7-11e7-9106-cb91c8266cc0.png">

**Comment by buzzdecafe** [comment]
uh-oh

**Comment by buzzdecafe** [comment]
seems to be working for me this morning

**Comment by jlengstorf** [comment]
Follow-up — it looks like this was an error caused by too much code in the REPL (my test object was a REST API response).

I deleted some of the response, and it now works.

Maybe a catch for the `400` that provides a helpful message (e.g. "There is too much code in the REPL to create a share link; please shorten the snippet and try again.")?

FYI, I also tried this on bit.ly, and it choked on the long URL as well.

I'll close this issue, since it's a different (and less scary-sounding) issue altogether. Let me know if you want me to create an issue for the error message.

**Comment by buzzdecafe** [comment]
thanks, an issue for this might be a good idea. if nothing else, at least someone who encounters this in the future might be able to find it and understand what is happening.
