### ISSUE TITLE
__ (double underscore) in the sample code of #where

### ISSUE THREAD

**Issue by scriptype** [ramda/ramda.github.io#177]
Problem is here: http://ramdajs.com/docs/#where. Unmentioned `__` variable is passed down to `gt` function two times:

```js
// ...
x: R.gt(__, 10),
y: R.lt(__, 20)
// ...
```

I couldn't find any mention about what this `__` thing is. And as I expected, when I try to run the example code, it doesn't work.

**Comment by buzzdecafe** [comment]
Nice catch. Should be `R.__`

**Comment by mrosata** [comment]
:+1: the docs should be 
```javascript
x: R.gt(R.__, 10),
y: R.lt(R.__, 20)
```
Maybe close this issue and open it in the main repo

**Comment by scriptype** [comment]
Created related pull-request in the main repo.
