### ISSUE TITLE
Missing dot leads to confusion

### ISSUE THREAD

**Issue by scriptype** [ramda/ramda.github.io#178]
http://ramdajs.com/docs/#aperture

> Returns a new list, composed of n-tuples of consecutive elements If n is greater than the length of the list, an empty list is returned.

It took me one or two seconds to figure out what's returned when :)

**Comment by buzzdecafe** [comment]
haha yeah, punctuation matters. Are you interested in a PR to fix this typo?

**Comment by scriptype** [comment]
I was looking to this issue yesterday and saw this:

https://github.com/ramda/ramda/blob/master/src/aperture.js#L8

I guess the problem will be gone after a new build for docs. Maybe I should close the issue?

**Comment by buzzdecafe** [comment]
ah! thanks for doing the research. Yes, I think this is good to close; i may try to publish a release this weekend

**Comment by scriptype** [comment]
That research help came from the awesome ramda community in gitter. ❤️
