### ISSUE TITLE
Open "Try in REPL" in separate tab

### ISSUE THREAD

**Issue by ivanzusko** [ramda/ramda.github.io#183]
Hello, everybody.

In my humble opinion, it's kinda annoying when you are on [docs](http://ramda/docs/) page and click on the `Try in REPL` it's opening REPL in the same tab. After all you need to press backspace to return back to the docs page. And more changes in REPL you did - more times you need to press backspace.

I'd like to make PR, can I assign it on myself?

**Comment by buzzdecafe** [comment]
This sounds like a good idea to me; I usually middle-click to spawn a new tab anyways, but on mobile, might be better to have the system spawn it.

So I'd be happy to see a PR for this. Thanks

**Comment by ivanzusko** [comment]
@buzzdecafe super :+1: will be done by the end of today.

**Comment by ivanzusko** [comment]
PR is ready: #184

**Comment by ivanzusko** [comment]
**PR** was merged, so I'm closing this _issue_ 🎉  😄
