### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by rafaelrozon** [ramda/ramda.github.io#196]
Hello,

First of all, thank you so much for Ramda. It's awesome!!

I would like to translate the documentation to Brazilian Portuguese. If you guys think that is a good a idea, please, let me know how I should proceed. 

Thank you.

**Comment by kedashoe** [comment]
Hi @rafaelrozon , that would be awesome! There is no formal process, but you can see how others have done it:

https://github.com/ramda/ramda/issues/1951
https://github.com/ramda/ramda/pull/2201

in particular this comment could be of use:

https://github.com/ramda/ramda/pull/2201#issuecomment-307977821

**Comment by rafaelrozon** [comment]
Thank you @kedashoe for the fast answer. 

I'll familiarize myself with the code base and how the other translations were done and I'll come up with a plan, probably by this weekend. 
I'll reach out if I have any question and when I have something. 

Thanks!

**Comment by kedashoe** [comment]
:+1:

**Comment by kedashoe** [comment]
That sounds about right to me, ping @adispring @ivanzusko , any thoughts?

**Comment by adispring** [comment]
@rafaelrozon ，Yes，the main procedure is right，you can refer to these repos: [ramdacn](https://github.com/ramdacn), I've written some script to help translation.

1. https://github.com/ramdacn/ramda/blob/coding-page-v0-25-0/scripts/pickComment.sh
2. https://github.com/ramdacn/ramda/blob/coding-page-v0-25-0/scripts/translate.sh

I also made a dir to store the original & translated comments:

https://github.com/ramdacn/ramda/tree/coding-page-v0-25-0/i18n

I'll explain more details about the translation latter.

**Comment by adispring** [comment]
@rafaelrozon ，my translating manual in Chinese, I'll translate this latter into English.

阶段一. ramda 仓库中的工作：

1. ramda 拉取最新原英文仓库 master 分支数据；
2. 将 coding-page 分支转回英文注释：./scripts/translate.sh -l=en-us，合并最新的 master 分支代码，解决冲突，提取英文注释到 i18n/en-us：./scripts/pickComment.sh -l=en-us 。这里要配合 sourceTree，观察每一步的变化，以防出错。
3. 对照英文 ramda 仓库最新 tag 和 上一次 tag 的改动进行中文翻译的增、删、改工作，对应工作目录为 i18n/zh-cn。修改完成后提交一次 commit。
4. 运行自动化翻译脚本：./scripts/translate.sh -l=zh-cn，将刚才的翻译添加到 src/*.js 的源文件中，中文注释替换英文注释。
5. 运行 npm run build，生成 dist/ramda.js 和 dist/ramda.min.js ，这两个文件即 ramda 仓库的翻译输出，要在 ramda.github.io/ 中用到。
6. 没有问题则运行：git push origin coding-pages:coding-pages， 


阶段二. ramda.github.io 中的工作：

1. ramda.github.io 拉取最新原英文仓库 master 分支数据；
2. 将 master 数据合并到 coding-page 分支上，解决冲突。
3. 将 阶段一 中生成的 ramda.js 文件 copy 到 docs/dist/ramda.js 中：cp ../../../ramda/dist/ramda.js ramda.js。
4. 运行 npm run jsdoc 或者 npm run make_release 生成新 tag 的静态网页，commit 一下。
5. 将 google analysis GA 代码加到 静态页面：包括 /index.html docs/index.html repl/index.html 中。
6. npm run server 调试一下，看下首页 和 /doc /repl 页有没有问题。
7. 没有问题则运行：git push coding coding-pages:coding-pages， 即可发布。

**Comment by adispring** [comment]
In the ramda.github.io repository, I have changed some config:

1. package.json
```js
"jsdoc": "jsdoc -c .jsdoc.config.json --destination ./docs --template . ../ramda/src",
```
change template directory to your translated ramda src directory, I put ramda and ramda.github.io in the same directory(ramdacn/), so the translated ramda src directory is `../ramda/src`.

2. get_ramda_file.js
```js
  ramda_folder = path.resolve('../ramda')

  var file_path = path.join(ramda_folder, child_path)
```

**Comment by ivanzusko** [comment]
@kedashoe ,
@adispring made an amazing job and very detailed instructions, but I'm still in my process of translation, so didn't try this approach 😞

**Comment by rafaelrozon** [comment]
Thank you @adispring @kedashoe. I'll go over the steps again and make sure I understand and get them right.

**Comment by adispring** [comment]
@rafaelrozon , Any questions or new ideas in translation, welcome to discuss. This is Chinese website of ramda: [ramda.cn](http://ramda.cn/).

**Comment by rafaelrozon** [comment]
Hey guys,

Sorry for the very late reply. I just wanted to let you know that I'm working on the translation. It'll take me some time. I'm thinking like 2 months maybe. Once I have some significant progress, I'll update you guys again. 

Thank you all for the help and the opportunity.
