### ISSUE TITLE
Trim and Keys has extra _ prefix

### ISSUE THREAD

**Issue by cht8687** [ramda/ramda.github.io#198]
I've submitted a PR in Ramda project to fix this issue. 
https://github.com/ramda/ramda/pull/2327

Once new build generated, this issue can be fixed automatically.

![keysandtrim](https://user-images.githubusercontent.com/4587603/31440003-144bd102-aeda-11e7-90f2-50959ecfd0d4.png)

**Comment by kedashoe** [comment]
https://github.com/ramda/ramda/pull/2327
