### ISSUE TITLE
Translate document for korean

### ISSUE THREAD

**Issue by hg-pyun** [ramda/ramda.github.io#202]
Hello!. I am software developer of korea. 
I want to contribute trasnlation document for korean language.
Would you tell me some contribute rules?

Thank you.

**Comment by kedashoe** [comment]
Hi @haegul , please see [this thread](https://github.com/ramda/ramda.github.io/issues/196). Some links (also linked in previous thread)

https://github.com/ramda/ramda/issues/1951
https://github.com/ramda/ramda/pull/2201

in particular this comment:

https://github.com/ramda/ramda/pull/2201#issuecomment-307977821
