### ISSUE TITLE
The favicon.ico's background is not transparent.

### ISSUE THREAD

**Issue by adispring** [ramda/ramda.github.io#205]
The website favicon.ico's background color is not transparent, but white, can anyone fix that?

**Comment by CrossEye** [comment]
Should it be transparent?  I imagine black-on-transparent would not look so great on the default dark gray background of my Ubuntu Firefox 58.

If this is a good idea, it should be trivial to create one.  A pull request would be welcome.  The SVGs are at http://ramda.jcphillipps.com/logo/.

**Comment by 8881** [comment]
https://github.com/ramda/ramda.github.io/pull/206
