### ISSUE TITLE
remove references to mergeDeep in 0.25 docs

### ISSUE THREAD

**Issue by karthikiyengar** [ramda/ramda.github.io#207]
There are references to `mergeDeep` in these sections, which is non-existent ATM.

<img width="670" alt="screen shot 2018-03-21 at 15 56 58" src="https://user-images.githubusercontent.com/8260207/37717364-b25b29f0-2d20-11e8-91f1-3d4ac36e6342.png">

I'd have done it myself, but I'm short on time, apologies.

**Comment by CrossEye** [comment]
Closing in favor of https://github.com/ramda/ramda/issues/2493.  The documentation is generated from the source code, so this belongs in the main Ramda repo.
