### ISSUE TITLE
Evolve example a bit misleading

### ISSUE THREAD

**Issue by davidchase** [ramda/ramda.github.io#21]
Hi,

So if you go to [evolve](http://ramdajs.com/docs/#evolve) the sample shows that if you add a `data` key to the transformer it will nest `elapsed` and `remaining` inside like so:
```js
//=> {firstName: 'Tomato', data: {elapsed: 101, remaining: 1399}}
```

However if you [try it out](http://bit.ly/1dPdp8J) the results are as followed:

```js
var tomato  = {firstName: '  Tomato ', elapsed: 100, remaining: 1400};
var transformations = {
  firstName: R.trim,
  lastName: R.trim,
  data: {elapsed: R.add(1), remaining: R.add(-1)}
};
R.evolve(transformations, tomato);

//=> {"elapsed": 100, "firstName": "Tomato", "remaining": 1400}
```

with no `data` key in sight :frowning: 

cheers david

**Comment by CrossEye** [comment]
Yes, a definite typo in there.  It [should read][re]

```js
    var tomato  = {firstName: '  Tomato ', data: {elapsed: 100, remaining: 1400}};
```



  [re]: http://bit.ly/1KTalar

**Comment by davidchase** [comment]
sure thing :+1:
