### ISSUE TITLE
Show function signature in document index

### ISSUE THREAD

**Issue by s97712** [ramda/ramda.github.io#212]
![image](https://user-images.githubusercontent.com/13390001/40419720-cc41cde6-5eb8-11e8-90d8-33b4a2d4853f.png)

Show function signature in there. That will find the function faster

**Comment by s97712** [comment]
I think can add a checkbox, show detials when it checked.
Like this

![tim 20180524132807](https://user-images.githubusercontent.com/13390001/40466014-372a59dc-5f56-11e8-8260-6d8391da0988.png)

**Comment by customcommander** [comment]
See #61
