### ISSUE TITLE
R.__ link is broken

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda.github.io#214]
<https://ramdajs.com/docs/#module.exports> should be <https://ramdajs.com/docs/#__>.

<https://ramdajs.com/docs/#_keys> and <https://ramdajs.com/docs/#_trim> also look wrong.

**Comment by CrossEye** [comment]
Yes, it's on my list.  I haven't had time over the last few days, but should this weekend.

https://github.com/ramda/ramda/issues/2542

**Comment by Koleok** [comment]
Was going to file a new issue but this appears to be related, `R.__` is showing up as `module.exports` in the docs currently
![image](https://user-images.githubusercontent.com/10928312/48206715-04edbe80-e33d-11e8-8bf0-5a3400bfee69.png)

**Comment by CrossEye** [comment]
Yes, we really need to release a new version.  This will be fixed when we do.

**Comment by rpearce** [comment]
This seems to be fixed
