### ISSUE TITLE
links inconsistent

### ISSUE THREAD

**Issue by Muhnad** [ramda/ramda.github.io#216]
links inconsistent with names that make a couple of links broken like:
R.keys && R.trim && R.__

the problem is in the {{name}}
```html
<a target="_blank" title="View source on GitHub" href="https://github.com/ramda/ramda/tree/v{{../version}}/source/{{name}}.js">
```

I think we have multi option to fix this:
1- rename the files to be _keys & _trim & module.exports(NO Please :D )
2- remove underscore from names in v0.25.0 
```diff
-var _keys = typeof Object.keys === 'function' && !hasArgsEnumBug
+var keys = typeof Object.keys === 'function' && !hasArgsEnumBug
```
3- make utility to remove underscore from {{name}} but this not valid with module.exports
4- replace {{name}} with something else refer to function name itself

**Comment by customcommander** [comment]
This doesn't seem to be an issue anymore. Could you verify and close if you're happy with the resolution please?
