### ISSUE TITLE
REPL slow initial load because of wzrd.in slow response

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [ramda/ramda.github.io#217]
Hi!

Ramda REPL used to load instantaneously, but ever since some assets got wired in through wzrd.in the page keeps loading until the response is back or it times out. This usually means waiting for 20+ seconds to fetch sanctuary@latest and ramda-fantasy@latest.

I assume wzrd.in is a CDN. I'm opening the REPL from Hungary, so I don't know, if it is a general issue affecting everyone, or is it just a few unoptimised regions, but it's definitely slow regardless of what computer, OS or browser I'm using.

<img width="1048" alt="kepernyofoto 2018-11-20 - 11 51 46" src="https://user-images.githubusercontent.com/2386064/48769426-e8963e00-ecbb-11e8-802b-5b12a7f020b8.png">

**Comment by meszaros-lajos-gyorgy** [comment]
Related issue: https://github.com/ramda/repl/issues/60

**Comment by CrossEye** [comment]
Anyone who wants to take a swing at this is welcome.  

https://bundle.run looks like it might be of help.

**Comment by CrossEye** [comment]
I think it's working now.

**Comment by kiliw** [comment]
Not fixed for me. Page load still takes a very long time.

**Comment by CrossEye** [comment]
Not sure what happened. I swear it was working last night...

Uggh!

**Comment by meszaros-lajos-gyorgy** [comment]
I temporarily blocked all requests towards wzrd.in and that kinda solved the situation for me.

**Comment by kiliw** [comment]
It is again super slow for me. Does someone else has this problem?

**Comment by CrossEye** [comment]
Oh yes.  It's still happening.  I haven't gotten any response to my request for help, so I think I'm going to have to dig into how the docs and repl are integrated.

**Comment by CrossEye** [comment]
@craigdallimore:

Thank  you.  If you have time, that would be great.  Or even if you have some pointers, that would be fine.  But if you don't find yourself with time, let me know, and I will try to muddle through.

I've not spent any real time with the REPL, and the last few times I've published, there were no REPL changes, so it wasn't a worry.  I do really need to learn some more.  If nothing else, there are several minor features I'd like to add.  (`Making tidy` a sticky checkbox, the same with `clear` -- to run between changes -- and, if possible, making the input/output separator draggable.)  But there's always so much to do.  I'm mostly focused on the possibility of 1.0 at the moment.

**Comment by craigdallimore** [comment]
@CrossEye I'm afraid I've struggled for time. I've got a PR at #219 which replaces the `wzrd.in` configuration with `bundle.run`; I hope this helps! I'm afraid I don't know too much about how deployment works.

**Comment by CrossEye** [comment]
Thanks, @craigdallimore.  I will try to figure it out.

**Comment by meszaros-lajos-gyorgy** [comment]
The new bundle.run is blazing fast! It responded back the content in like 30-40 ms! The ticket can be closed!

**Comment by CrossEye** [comment]
Thanks @craigdallimore!  It looks like when I changed the REPL repo, it didn't do anything, but that such was never the correct place to make the change.  Once done in the docs repo, there was no separate deployment necessary!  Woohoo! :fireworks:

**Comment by xtuc** [comment]
Hey, please let me know if I can help with `bundle.run` (i'm running it).

**Comment by CrossEye** [comment]
@xtuc: Thank you.  We seem to have gotten this running well using bundle.run.  We actually have a mix of sources now, and perhaps we should clean that up; maybe bundle.run could be a one-stop shopping site for everything we include.  If that would be possible, I think it would be useful.  You can see the network traffic on https://ramdajs.com/repl/ for details.
