### ISSUE TITLE
Try Ramda should use uncompressed version of ramda

### ISSUE THREAD

**Issue by jethrolarson** [ramda/ramda.github.io#22]
e.g.
```function (r){return function(e){return Pr(function(n){return t(n,e)},r(n(e)))}}``` is hard to decipher when your code isn't working.

**Comment by davidchase** [comment]
:+1: though it looks like the cdn from `cdn.jsdelivr.net` doesn't host the uncompressed version so maybe switching to using `cdnjs.cloudflare.com`

**Comment by CrossEye** [comment]
I'd rather see if we can include the unminified one as well in jsdelivr, as they also have the `latest` feature, which is useful for the repl.  I meant to do this earlier in the week.  I will try to look into it this weekend.

**Comment by buzzdecafe** [comment]
seems to be using uncompressed latest now, so closing this
