### ISSUE TITLE
RawGit is shutting down

### ISSUE THREAD

**Issue by isiahmeadows** [ramda/ramda.github.io#222]
I noticed the REPL source itself is currently loaded through RawGit, via `https://cdn.rawgit.com/ramda/repl/1.1.0/dist/bundle.js` and `https://cdn.rawgit.com/ramda/repl/1.1.0/dist/bundle.css`. However, [RawGit is shutting down](https://rawgit.com/), so this isn't sustainable.

I feel you could just serve it through ramdajs.org directly. You can keep it updated through a script either here or in the REPL's repo, and it's likely to work even with the most restrictive and overzealous blockers, as long as they allow scripting in the first place.

**Comment by CrossEye** [comment]
Thanks.  We have some other work to do on the REPL; I'm hoping someone who knows that code better will pick this up.  But if not I'll try to do it myself soon.

**Comment by isiahmeadows** [comment]
For my suggestion of just hosting them locally, it would just involve a build-time script to fetch these two files and save them somewhere locally:

- `https://raw.githubusercontent.com/ramda/repl/master/package.json` to fetch the current version
- `https://raw.githubusercontent.com/ramda/repl/${pkg.version}/dist/bundle.css`
- `https://raw.githubusercontent.com/ramda/repl/${pkg.version}/dist/bundle.js`

<details>
<summary>It could be as simple as this:</summary>

```js
// Assuming this is in the project root somewhere - depends on node-fetch,
// obviously
"use strict"
const fs = require("fs")
const path = require("path")
const {pipeline} = require("stream")
const fetch = require("node-fetch")

const repl = (h, p) => `https://raw.githubusercontent.com/ramda/repl/${h}/${p}`
const local = p => path.resolve(__dirname, p)

const save = (src, dest) =>
    fetch(src).then(res => pipeline(res.body, fs.createWriteStream(dest)))

fetch(repl("master", "package.json"))
.then(res => res.json())
.then(pkg => {
    save(repl(pkg.version, "dist/bundle.css"), local("repl.css"))
    save(repl(pkg.version, "dist/bundle.js"), local("repl.js"))
})
```
</details>

**Comment by Kreijstal** [comment]
just use rawgit.org
