### ISSUE TITLE
documentation for R.otherwise refers to renamed R.then

### ISSUE THREAD

**Issue by k-yle** [ramda/ramda.github.io#238]
https://ramdajs.com/docs/#otherwise refers multiple times to `R.then`, and has a broken link "See also: then". It should be `R.andThen` as of v27

**Comment by CrossEye** [comment]
Thank you for the report.  If you're interested in creating a PR to fix this, it would go in the main Ramda repo; the docs are generated from the JSDoc tags in files in the [ramda/source][rs] folder.


  [rs]: https://github.com/ramda/ramda/tree/master/source

**Comment by k-yle** [comment]
looks like it's already fixed in master... https://github.com/ramda/ramda/blob/master/source/otherwise.js#L19
