### ISSUE TITLE
REPL: ramda-fantasy and sactuary scripts failing to load

### ISSUE THREAD

**Issue by jay-jlm** [ramda/ramda.github.io#241]
Both fail with error 500 or 503.

If I try the same operation directly  on the bundle.run website, I get either the same thing or this error:

> server error
> Please raise an issue, quoting this URL.
> package has no entry file; please specify a `module` key in your `package.json`.

**Comment by CrossEye** [comment]
Just back from a vacation.  I will look into this as soon as I can.

**Comment by customcommander** [comment]
@jay-jlm This doesn't seem to be an issue anymore. Could you please check and close this issue if you're happy with the resolution?

![Uploading Screenshot 2022-01-19 at 22.59.43.png…]()
