### ISSUE TITLE
In ramda home page: ramda version does follow release version

### ISSUE THREAD

**Issue by adispring** [ramda/ramda.github.io#246]
In ramda v0.27.0 home page, installation section: version should be 0.27.0 instead of 0.25.0. as follows:

or from a CDN, either cdnjs:

```js
<script src="//cdnjs.cloudflare.com/ajax/libs/ramda/0.25.0/ramda.min.js"></script>
```

or one of the below links from jsDelivr:

```js
<script src="//cdn.jsdelivr.net/npm/ramda@0.25.0/dist/ramda.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/ramda@0.25/dist/ramda.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/ramda@latest/dist/ramda.min.js"></script>
```

**Comment by CrossEye** [comment]
Some build process should have taken care of this.  We really need to rework that process.

**Comment by CrossEye** [comment]
Do you want to update this?

**Comment by adispring** [comment]
I find out that Home page is created by ramda/ramda repository's README.md, so I write a script to update the version before publish:

https://github.com/ramda/ramda/pull/3082

**Comment by customcommander** [comment]
@adispring I am closing this. As you found out the home page of the documentation is taken from the ramda repo's README directly. I'll have a look at your PR this week.
