### ISSUE TITLE
Bug in documentation for partialObject

### ISSUE THREAD

**Issue by customcommander** [ramda/ramda.github.io#261]
https://ramdajs.com/docs/#module.exports

![Screenshot 2022-01-16 at 20 23 05](https://user-images.githubusercontent.com/681975/149676720-76cbb4bd-237b-423e-af50-36dd6ad62b9a.png)

Unfortunately that function doesn't appear property on the documentation site following the 0.28.0 release. I can confirm that the function _is_ available:

```shell
$ node
Welcome to Node.js v12.20.0.
Type ".help" for more information.
> var {partialObject} = require('ramda');
undefined
> partialObject;
[Function: f2]
> 
```

The bug is most likely in the processing of the JSDoc blocks.

**Comment by CrossEye** [comment]
As a very temporary fix, I changed the generated HTML.  I've been in the JSDoc generating code before, but it's been many years.

If anyone has an idea, I'd love to hear it.  But I can dig into this soon.

**Comment by customcommander** [comment]
@CrossEye I think I've got an idea. Already looking into it.

**Comment by customcommander** [comment]
Ok I found the issue.

Most functions are assigned to a symbol. The symbol is documented then exported e.g.,

```javascript
/**
 * A function that always returns `true`. Any passed in parameters are ignored.
 *
 * @func
 * @memberOf R
 * @since v0.9.0
 * @category Function
 * @sig * -> Boolean
 * @param {*}
 * @return {Boolean}
 * @see R.F
 * @example
 *
 *      R.T(); //=> true
 */
var T = function() {return true;};
export default T;
```

However in this case the function was inlined with the export statement and the JSDoc block:

```javascript
/**
 * Takes a function `f` and an object, and returns a function `g`.
 * When applied, `g` returns the result of applying `f` to the object
 * provided initially merged deeply (right) with the object provided as an argument to `g`.
 *
 * @func
 * @memberOf R
 * @since v0.28.0
 * @category Function
 * @sig (({ a, b, c, ..., n }) -> x) -> { a, b, c, ...} -> ({ d, e, f, ..., n } -> x)
 * @param {Function} f
 * @param {Object} props
 * @return {Function}
 * @see R.partial, R.partialRight, R.curry, R.mergeDeepRight
 * @example
 *
 *      const multiply2 = ({ a, b }) => a * b;
 *      const double = R.partialObject(multiply2, { a: 2 });
 *      double({ b: 2 }); //=> 4
 *
 *      const greet = ({ salutation, title, firstName, lastName }) =>
 *        salutation + ', ' + title + ' ' + firstName + ' ' + lastName + '!';
 *
 *      const sayHello = R.partialObject(greet, { salutation: 'Hello' });
 *      const sayHelloToMs = R.partialObject(sayHello, { title: 'Ms.' });
 *      sayHelloToMs({ firstName: 'Jane', lastName: 'Jones' }); //=> 'Hello, Ms. Jane Jones!'
 * @symb R.partialObject(f, { a, b })({ c, d }) = f({ a, b, c, d })
 */

export default _curry2((f, o) => (props) => f.call(this, mergeDeepRight(o, props)));
```

JSDoc can infer a lot of things when parsing the AST and therefore can automatically give a name to the function. But in this case it's impossible. We can help JSDoc by documenting the name of the symbol with `@name`.

Here's a silly example:

```javascript
/**
 * Takes a function `f` and an object, and returns a function `g`.
 * When applied, `g` returns the result of applying `f` to the object
 * provided initially merged deeply (right) with the object provided as an argument to `g`.
 *
 * @func
 * @name FOOBARBAZ
 * @memberOf R
 * @since v0.28.0
 * @category Function
 * @sig (({ a, b, c, ..., n }) -> x) -> { a, b, c, ...} -> ({ d, e, f, ..., n } -> x)
 * @param {Function} f
 * @param {Object} props
 * @return {Function}
 * @see R.partial, R.partialRight, R.curry, R.mergeDeepRight
 * @example
 *
 *      const multiply2 = ({ a, b }) => a * b;
 *      const double = R.partialObject(multiply2, { a: 2 });
 *      double({ b: 2 }); //=> 4
 *
 *      const greet = ({ salutation, title, firstName, lastName }) =>
 *        salutation + ', ' + title + ' ' + firstName + ' ' + lastName + '!';
 *
 *      const sayHello = R.partialObject(greet, { salutation: 'Hello' });
 *      const sayHelloToMs = R.partialObject(sayHello, { title: 'Ms.' });
 *      sayHelloToMs({ firstName: 'Jane', lastName: 'Jones' }); //=> 'Hello, Ms. Jane Jones!'
 * @symb R.partialObject(f, { a, b })({ c, d }) = f({ a, b, c, d })
 */
```

<img width="805" alt="Screenshot 2022-01-18 at 21 13 46" src="https://user-images.githubusercontent.com/681975/150020577-ab4c4ea4-4194-4783-9dd4-e40b0cfaed6d.png">

To fix this we need to update the JSDoc block in the ramda repo.

If you don't object I think we should pull `ramda` as a dependency of this repo not from NPM but from GitHub. This way we can more easily deploy documentation update without having to make releases.

**Comment by CrossEye** [comment]
> If you don't object I think we should pull `ramda` as a dependency of this repo not from NPM but from GitHub. This way we can more easily deploy documentation update without having to make releases.

That makes some sense.  I think that would require keeping around a `fix` branch so that the docs don't start including code merged but not published.  Or is there something simpler that I'm missing?

**Comment by adispring** [comment]
Maybe we can add eslint-plugin-jsdoc to help checking nessary jsdoc field is included.

**Comment by CrossEye** [comment]
@adispring: Sure we could.  But I'd rather simply fix this function to act like the others.  A `name` tag would mostly be redundant.

**Comment by adispring** [comment]
> @adispring: Sure we could. But I'd rather simply fix this function to act like the others. A `name` tag would mostly be redundant.

Agree. Automatically check if `fnName` exist in `export default fnName` may be better than check if `@name` exist.

**Comment by customcommander** [comment]
See https://github.com/ramda/ramda/pull/3221
