### ISSUE TITLE
In ramda doc, Runkit throw Error with node version 17 and 16

### ISSUE THREAD

**Issue by adispring** [ramda/ramda.github.io#262]
When click "run it here" in ramda doc, Runkit will throw Error:

![image](https://user-images.githubusercontent.com/9584123/149858277-93e79b67-ff25-4510-9f18-60216d25e258.png)

I found that runkit using node v17 as default version, which will throw Error.

When switch to v16, program can run, but will display a warning below the result, when switch to version less than or equal to v15, the program works fine.

**Comment by tolmasky** [comment]
Node 16 provides more information:

> (node:1) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./src/" in the "exports" field module resolution of the package at /app/available_modules/1642518149000/ramda-fantasy/node_modules/ramda/package.json.
> Update this package.json to use a subpath pattern like "./src/*".
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 

So we get this deprecation warning in node 16, and then node 17 fully drops support for this it seems. We should change `nodeVersion: '*'` to `nodeVersion: '14.x.x'` until ramda supports this new subpath pattern.

**Comment by CrossEye** [comment]
I merged the PR that fixes this.  But I'm not following what the long-term fix is.  I'm reading it as something like

> Don't use the deprecated `./src/`.  Instead use `.src/`

Somehow I don't think that's right.  Are we supposed to put this in a different field?
