### ISSUE TITLE
Mistake in `takeLast` example

### ISSUE THREAD

**Issue by myst729** [ramda/ramda.github.io#27]
The second line in `takeLast` examples is incorrect:

```js
R.takeLast(2, ['foo', 'bar', 'baz']); //=> ['for', 'baz']
```

According to the function description, the output should be `['bar', 'baz']`

**Comment by davidchambers** [comment]
Thanks, @myst729. The error in the source code was corrected in ramda/ramda#1322. The website will be updated when we publish the next version of Ramda.
