### ISSUE TITLE
In ramda doc, Runkit throw different Errors with different node version

### ISSUE THREAD

**Issue by adispring** [ramda/ramda.github.io#281]
In node 14, runkit throws: "Cannot find module 'ramda@0.29.0'"
In node 18, runkit throws: "Error: './src/curry' is not defined"

@tolmasky Can you give some help about this?

**Comment by tolmasky** [comment]
It appears that for some reason the latest we have available on RunKit is 0.29.0. We're looking into why the 0.29.0 version wasn't picked up and hopefully should have it available shortly. This seems to be the source of the issues here. Unfortunately, given that it is Easter weekend, the person who can most easily figure this out might not be able to get to it until Monday, but I am trying to reach out to him right now. As a stop gap, you could just use "ramda" or "ramda@0.28.0" as that version is available.

**Comment by tolmasky** [comment]
Hi @adispring, it should now be fixed thanks to @ pouwerkerk! Please let us know if you are still having issues.

**Comment by adispring** [comment]
> Hi @adispring, it should now be fixed thanks to @pouwerkerk! Please let us know if you are still having issues.

Yes, it works again. Thanks @tolmasky and @pouwerkerk
