### ISSUE TITLE
Unable to reach docs for version 0.29.1

### ISSUE THREAD

**Issue by mattcobley** [ramda/ramda.github.io#284]
Hi all,

I frequently need to refer to the docs for older versions that the current one. At present there isn't a way in the UI that I can see to switch between versions in the docs, so firstly it'd be great if that could be implemented. Failing that, I've previously used a URL like https://ramdajs.com/0.27.0/docs/ to reach previous versions of the docs (found by messing around with the URL). This has been useful, but I don't seem to be able to reach the docs for 0.29.1 or 0.29.0, and can see that this repo does not have a folder for those versions - has something changed in how old docs are handled? Obviously the older versions do need their docs available for people who use the library, so I would hope that this isn't something that's been done deliberately?

Thanks very much in advance for your help! Love the library of course :-)

**Comment by kedashoe** [comment]
ty for raising the issue @mattcobley . This should definitely be supported. If someone wants to take a look at this please reply here, otherwise I'll take a look when I can

**Comment by kedashoe** [comment]
@mattcobley could you test this now? If everything has gone as planned there should be a dropdown now to navigate to different versions

![Screenshot_2024-08-20_09-07-23](https://github.com/user-attachments/assets/a877795f-653e-40d2-af1c-93620d1fb6f2)

[https://ramdajs.com/0.29.1/docs/](https://ramdajs.com/0.29.1/docs/)

**Comment by mattcobley** [comment]
> @mattcobley could you test this now? If everything has gone as planned there should be a dropdown now to navigate to different versions
> 
> ![Screenshot_2024-08-20_09-07-23](https://private-user-images.githubusercontent.com/719519/359557087-a877795f-653e-40d2-af1c-93620d1fb6f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzE3NDEsIm5iZiI6MTcyNDE3MTQ0MSwicGF0aCI6Ii83MTk1MTkvMzU5NTU3MDg3LWE4Nzc3OTVmLTY1M2UtNDBkMi1hZjFjLTkzNjIwZDFmYjZmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxNjMwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGQyNWU2NDkyM2ZhNzBmYWM4ZTE2MTAzM2YzZjE5ZDYyYmNkNDRiNzcxZjhjNzUyYjBhMzcwY2M1ZmM2ZWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rDbYWdxZ3nFprzRBIoOk6J9_fCthQQ8UW7JBtk9jsG4)
> 
> https://ramdajs.com/0.29.1/docs/

Amazing, thank you for doing that - all looks good to me!! Have tested it out with the `propEq` argument changes, and works for me inc the REPL. Thank you!!

Future improvement would be to not clear the search results when you switch versions, but certainly happy to close for now.
