### ISSUE TITLE
Documentation for older versions gone

### ISSUE THREAD

**Issue by TheLudd** [ramda/ramda.github.io#286]
Hello. 
I noticed today that documentation for older versions are gone. We are still on 0.15.1 and due to many breaking changes, we hesitate to upgrade. Is there a possibility of restoring these older versions?

**Comment by kedashoe** [comment]
We previously had a folder for 0.15, which appears to actually contain docs for 0.15.1. I've restored that:

https://ramdajs.com/0.15/docs/

Unfortunately generating the docs for 0.15 using the current setup does not work. I tried some quick fixes but couldn't get it. So we can't switch to 0.15 and away from it easily. If you click the repl from 0.15 I think the repl should work? But it'll show the dropdown saying the current version.

**Comment by TheLudd** [comment]
I can see that it is restored. Team here very happy.
Thank you for fixing this
