### ISSUE TITLE
Documentation for eqDeep is missing

### ISSUE THREAD

**Issue by ccapndave** [ramda/ramda.github.io#29]

**Comment by davidchambers** [comment]
`R.eqDeep` was deprecated in [v0.15.0][1] and removed in [v0.16.0][2]. [`R.equals`][3] now provides [value-based equality][4]. :)


[1]: https://github.com/ramda/ramda/issues/1186
[2]: https://github.com/ramda/ramda/issues/1277
[3]: http://ramdajs.com/docs/#equals
[4]: https://github.com/ramda/ramda/pull/1096

**Comment by ccapndave** [comment]
Aha!  Thanks very much :)

**Comment by ccapndave** [comment]
Maybe the documentation for `R.equals` should still be updated because it just says 'Returns true if its arguments are equivalent' which sounds a bit ambiguous.

**Comment by davidchambers** [comment]
I agree that the description could be clearer. We should give an idea of what is meant by "equivalent".

The problem with JavaScript is that one can never actually know how a function will behave in every case without reading the source code.
