### ISSUE TITLE
FR: Auto complete in web REPL

### ISSUE THREAD

**Issue by hemanth** [ramda/ramda.github.io#31]
Auto complete or tab complete on `R.`

**Comment by CrossEye** [comment]
I'd love to see a PR for this.  I actually don't know the REPL code very well.  But I think it would be great behavior to have.

**Comment by hemanth** [comment]
Well, we would do something like what [esprima](http://esprima.org/demo/autocomplete.html) does or looks for few good node modules out there.

P.S: I would like to hear more options from who have worked on the REPL code :+1:

**Comment by davidchase** [comment]
With CodeMirror you can achieve <kbd>tab</kbd> complete for `R.` or really any valid key combination i did that in my ramtuary setup it works essentially with any global object.

**Comment by hemanth** [comment]
@davidchase Awesome, it would be great if we could apply the learning from ramtuary's REPL here and port this to babel :+1:

**Comment by CrossEye** [comment]
...or perhaps simply replace our REPL with the Ramtuary one, if David is interested.

There seems to have been a profusion of interest in REPLs recently.  And I hope that some of that can fold back into Ramda's REPL, which was always just a quick hack.  I would love to get a more robust solution.

**Comment by davidchase** [comment]
I am up for whatever you guys want do in terms of the Ramda REPL...

**Comment by MattMS** [comment]
Should this issue be migrated over to the [REPL repo](https://github.com/ramda/repl)?

**Comment by buzzdecafe** [comment]
> Should this issue be migrated over to the REPL repo?

Yes, well spotted

**Comment by hemanth** [comment]
[repl#26](https://github.com/ramda/repl/issues/26)
