### ISSUE TITLE
Missing font files

### ISSUE THREAD

**Issue by raine** [ramda/ramda.github.io#33]
The symptom is square boxes on the page.

![screen shot 2015-09-26 at 12 47 21](https://cloud.githubusercontent.com/assets/11027/10116911/c61b5586-644c-11e5-808d-464e9c2e6687.png)

![screen shot 2015-09-26 at 12 46 45](https://cloud.githubusercontent.com/assets/11027/10116909/b8bfdd4e-644c-11e5-9b7e-a34812e0c126.png)

**Comment by CrossEye** [comment]
Me?  I thought _you_ had them!

**Comment by scott-christopher** [comment]
It only appears to be an issue on http://ramdajs.com/docs/. The version URLs seem to load them fine, e.g. http://ramdajs.com/0.17/docs/

**Comment by scott-christopher** [comment]
Perhaps we should just switch to a single stylesheet for the whole site and use absolute paths to reference the stylesheet and fonts?

**Comment by CrossEye** [comment]
Maybe, but that's often a pain when you're testing locally.

**Comment by scott-christopher** [comment]
Otherwise we could symlink them into the version folders, which github pages allegedly supports.

**Comment by buzzdecafe** [comment]
> Maybe, but that's often a pain when you're testing locally.

since #51 was merged that pain should ameliorated. I think @scott-christopher 's suggestion "switch to a single stylesheet for the whole site and use absolute paths" is a simple, straightforward fix

**Comment by MattMS** [comment]
This seems fixed? (Chrome 54 on Windows 10)
