### ISSUE TITLE
Docs "See also" link issue

### ISSUE THREAD

**Issue by raine** [ramda/ramda.github.io#37]
http://ramdajs.com/docs/#reduce
http://ramdajs.com/docs/#map

<img width="655" alt="screen shot 2015-10-18 at 10 17 29" src="https://cloud.githubusercontent.com/assets/11027/10563052/7af5da22-7581-11e5-94c3-16d488cdead4.png">

**Comment by CrossEye** [comment]
Ok, this is clearly just the tag misplaced in the documentation.  That's a trivial fix.  But I'm not sure how to rerun the documentation except against the 0.18.0 tag.

Does anyone know of an easy way to make a new tag by just adding a minor commit to 0.18.0?  That would be our best bet.  @davidchambers?/

**Comment by davidchambers** [comment]
@CrossEye, are you saying the `@see` is misplaced because annotations must only appear *after* the description? I had not been aware of this restriction.

**Comment by branneman** [comment]
Technically you're splitting the `@description` into 2 parts, which is not legal jsdoc.

See: http://usejsdoc.org/tags-description.html
> If you describe a symbol at the very beginning of a JSDoc comment, before using any block tags, you may omit the `@description` tag.

**Comment by davidchambers** [comment]
I will sort this out.
