### ISSUE TITLE
Totally messed up on mobile

### ISSUE THREAD

**Issue by creynders** [ramda/ramda.github.io#41]
Not sure whether it's meant to be viewed on mobile, but it's totally unusable ATM.

![img_4393](https://cloud.githubusercontent.com/assets/436347/11295852/ac39130e-8f6e-11e5-83e7-23186afa6cc8.PNG)

This is on iOS 8.1.3.

**Comment by CrossEye** [comment]
There is a known issue at this URL: http://ramdajs.com/docs/.  We shouldbe fixing that soon.  Is that where you're seeing the problem?  The docs are usually viewed from http://ramdajs.com/0.18.0/docs/.  Does that one work properly for you?

**Comment by stevenbenisek** [comment]
Note that #122 only partially fixes this for Android < 4.3 (there are some other issue with `position: fixed`). iOS < 9 does work as expected after applying the fixes in #122.
