### ISSUE TITLE
Browser back button does not work properly in docs

### ISSUE THREAD

**Issue by wolfgang42** [ramda/ramda.github.io#42]
Example:
1. Visit http://ramdajs.com/0.18.0/docs/
2. Under `add` it says "See also `subtract`", so click that.
3. Click the browser back button.

**Expected result:** the page jumps back to `add`.
**Actual result:** The URL changes, but the page does not scroll.

I assume this is the result of some JavaScript controlling the links, though a cursory poke through the source doesn't reveal anything obvious.

**Comment by buzzdecafe** [comment]
i think this bit of nastiness may be sufficient to fix this problem:

```js
window.addEventListener('hashchange', function() { location.href = location.href; });
```

will try to open a pr for this presently
