### ISSUE TITLE
mysterious REPL behaviour when using lens named "name"

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda.github.io#43]
[This][1] works as expected:

```javascript
var _name = R.lensProp('name');

R.view(_name, {name: 42});
```

[This][2], on the other hand, does not:

```javascript
var name = R.lensProp('name');

R.view(name, {name: 42});
```

Perhaps the object to which a property is being assigned has a read-only `name` property?

[1]: http://ramdajs.com/repl/?v=0.19.0#var%20_name%20%3D%20R.lensProp('name')%3B%0A%0AR.view(_name%2C%20%7Bname%3A%2042%7D)%3B%0A
[2]: http://ramdajs.com/repl/?v=0.19.0#var%20name%20%3D%20R.lensProp('name')%3B%0A%0AR.view(name%2C%20%7Bname%3A%2042%7D)%3B%0A

**Comment by CrossEye** [comment]
Yes, it's bizarre, but there are several odd quirks in this REPL.  It really could use some love.  Anyone interested in taking it on?

@raine?  @davidchase?

**Comment by davidchase** [comment]
not an issue with ramtuary http://goo.gl/TyHqZ7 :stuck_out_tongue_closed_eyes: 

so i guess the question if you guys would like to include ramtuary in place of ramda repl, what is expected?

i can PR it minus the sanctuary and ramda-fantasy stuff, you probably don't need the babel polyfill or maybe you would like it?

i also bundle it with browserify but there's always the potential of using rollup instead

thoughts?

**Comment by CrossEye** [comment]
Actually, I'd prefer to keep most of the Ramtuary functionality intact.  I think including Sanctuary and Ramda-Fantasy would be an improvement (although it would be really nice if there were checkboxes to turn them off.)  And Babel would be a step in the right direction.  I don't care much between browserify and rollup.  I've not yet even tried rollup, to be honest.  The one important thing I don't think is there now is a version selector for Ramda.

I'm not looking for all this -- certainly not now -- but in my ideal world this would be skinned to look like any other page on http://ramdajs.com, living perhaps at first at a different path (`/try` ?) until it seemed ready to be the main REPL.  Even better would be if, when we decided to point the path to this version, old links would continue to work in the new version; if there was a Ramda version in the URL, it would be included, and Sanctuary and Ramda-Fantasy would simply default to `latest`.  That might be too much to ask for, though, and I wouldn't let not being able to do it stop me from improving the REPL as we can.

My bigger dreams includes something that might not be possible, but could be very useful, if the REPL would output more than the last expression.  Perhaps it could respond to the same token we use in our examples: `//=>`.  This would also be very useful in letting us automatically link code examples from the documentation to the REPL.

So I discussed all sorts of possible extensions.  Honestly, if we could simply port over the existing code onto the Ramda site, I'd be thrilled.

**Comment by davidchase** [comment]
thats sounds great i like those ideas... i will try to send in a PR tomorrow during day but most likely after work :+1:

**Comment by CrossEye** [comment]
Wonderful!  Please let me know what I can do to help.

**Comment by buzzdecafe** [comment]
:tada: 

i much prefer the ramtuary repl and would love to see it replace the current one sooner rather than later. In fact, right away. Then the rest of the items on @CrossEye 's wish list can be integrated _ad libitum_.

**Comment by CrossEye** [comment]
@buzzdecafe:

Agreed; the only thing that gives me pause is all the links to the current REPL that will be completely useless if we don't support the version in the URL.

**Comment by davidchase** [comment]
sorry didnt have chance last night, got swamped... forking the repo now... :smile:

**Comment by davidchase** [comment]
quick update, i was able to port over the repl to the ramda fork, but babel is giving me some issues so i will try to resolve that before submitting a PR

**Comment by davidchase** [comment]
PR #44

**Comment by buzzdecafe** [comment]
this issue looks fixed to me
