### ISSUE TITLE
Styles for printing

### ISSUE THREAD

**Issue by jakubrohleder** [ramda/ramda.github.io#66]
I just stumbled upon this library and it looks really awesome! Unfortunately reading whole documentation on the screen is pretty hard (at least for me). I tried to print it, but it seems that print styles are really messed up.

So I got this small, humble request: please fix them, it will be very helpful to make printing possible (especially for beginners).

**Comment by davidchambers** [comment]
This would be nice, I agree. :)

**Comment by MattMS** [comment]
From a very quick look, the print output code be cleaned up by hiding `body > aside` and `a[title="View source on GitHub"]`.
Maybe the first could have an `id` attribute and the links could have classes added to make it simpler to target and hide them in CSS?

**Comment by jakubrohleder** [comment]
I did some experiments today and the main idea is to:

- hide `body > aside`
-  hide `[title="View source on GitHub"]`
- hide `.navbar`
- set `position: static` for `html.docs-page main`
- lower `h2` font size and some spaces between paragraphs
- maybe add some title header

It doesn't seem to be very difficult task, if no one else has time I can prepare PR by the weekend.

**Comment by CrossEye** [comment]
We'd absolutely welcome a PR.  I think I once tested the print styles -- when we first created JSDoc style documentation -- and thought at the time, "tolerable but could use work."  I don't think I've looked at them since.  It would be great to clean them up.

**Comment by buzzdecafe** [comment]
@jakubrohleder i think we'd all be grateful for a PR
