### ISSUE TITLE
rename repository

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda.github.io#68]
In my view ramda-site would be a nicer name for this repository. Do we need to stick with ramda.github.io in order for the GitHub Pages wiring to work?

**Comment by CrossEye** [comment]
I agree that it would be a better name but believe we do have to stick with what we have.    Or at least that's the default.   From https://pages.github.com:

> If the first part of the repository doesn’t exactly match your username, it won’t work, so make sure to get it right.

**Comment by davidchambers** [comment]
The quote applies to a "user or organization site", which is what we're currently using. We could use a "project site" instead; we'd need to update `ramdajs.com` to point to `ramda.github.io/ramda-site`.

**Comment by buzzdecafe** [comment]
no objection here to a move/rename here. I do prefer the name "ramdajs.com" to "ramda-site" though

**Comment by CrossEye** [comment]
No objection either.

However, the only real reason this is in a separate repo was to take advantage of this.  If we want to make this sort of move, should we consider folding this back into the main Ramda repo?  A separate docs repo has always seemed to me just an artifact of how we're using GitHub.

**Comment by davidchambers** [comment]
> A separate docs repo has always seemed to me just an artifact of how we're using GitHub.

I appreciate having the issues live in separate places, but I can see arguments both ways. :)

**Comment by CrossEye** [comment]
> I appreciate having the issues live in separate places

It's not been a big deal, just a lot less discoverable.  If this were part of the main repo, we'd perhaps have to be better with tagging issues, but I think that's about it.

**Comment by MattMS** [comment]
I think sticking to the GitHub naming convention does make it quicker to identify the repo.

Also, would the ramda.github.io to ramdajs.com redirect still work with a different name?

**Comment by davidchambers** [comment]
> Also, would the ramda.github.io to ramdajs.com redirect still work with a different name?

Yep. We'd just need something like plaid/sanctuary-site#4.

**Comment by MattMS** [comment]
Cool. I was more thinking if the domain name would still resolve if there wasn't a repo with that name, but I guess if you have it working for Sanctuary then that answers the question. :smile:
