### ISSUE TITLE
Difference should link to symmetricDifference, and vice-versa.

### ISSUE THREAD

**Issue by decoursin** [ramda/ramda.github.io#72]
In [the documentation for difference](http://ramdajs.com/0.20.1/docs/#difference), there's a "See also differenceWith", but it should be "See also differenceWith, symmetricDifference."

Likewise, for differenceWith, symmetricDifference and symmetricDifferenceWith.

**Comment by CrossEye** [comment]
Agreed.  A [Pull Request][pr] regarding those source files would be welcome.

  [pr]: https://github.com/ramda/ramda/pulls

**Comment by decoursin** [comment]
Yeah, sorry, thank you so much for your help in creating this wonderful project. Until, I can get out of debt (college grad without a job), I'm going to elude doing such things.

**Comment by CrossEye** [comment]
Someone else will probably get around to it soon.  It's not a big deal.  Reopening so that we don't lose track of this.

I'm not quite sure what your circumstances have to do with creating a PR, but that's not really my lookout.  Glad you like the library.

**Comment by MattMS** [comment]
Should this issue be copied to the ramda repo since the change is there? https://github.com/ramda/ramda/blob/master/src/difference.js#L17

That said, given the docs would still need to be rebuilt, I can see why this issue is still valid.

**Comment by MattMS** [comment]
Appears fixed.

**Comment by buzzdecafe** [comment]
thanks @MattMS
