### ISSUE TITLE
Multiple types are not shown in "expand parameters" in documentation

### ISSUE THREAD

**Issue by CrossEye** [ramda/ramda.github.io#74]
When there are several possible types for a parameter, only the first one is shown when clicking "expand parameters" in the documentation. For example for "pluck" in the code we have [`@param {Number|String} key`](https://github.com/ramda/ramda/blob/master/src/pluck.js#L15) . However only `Number` is display in the expand parameter box.

(Moved from https://github.com/ramda/ramda/issues/1718. @jagare)

**Comment by CrossEye** [comment]
Anyone want to take a stab at fixing our JSDoc template to fix this?

**Comment by MattMS** [comment]
I'm happy to have a poke around at this, but my JSDoc skills are absolute beginner so I'd be happy for anyone to snipe it from me.

Here's where I'm starting to peek: https://github.com/MattMS/ramda.github.io/blob/master/docs/index.html.handlebars#L86

**Comment by CrossEye** [comment]
That makes sense.  I would also look at 

    https://github.com/MattMS/ramda.github.io/blob/master/docs/index.html.handlebars#L71-L77

for samples of repeating values.

Thanks!

**Comment by MattMS** [comment]
@CrossEye that code helped, thanks!
