### ISSUE TITLE
Take out bootstrap?

### ISSUE THREAD

**Issue by gaurav21r** [ramda/ramda.github.io#84]
Fantastic documentation site! Like really! :100:  We are using a fork of this for our own internal projects!

One thing we encountered was that `style.css` has bootstrap mixed into it! Maybe including a themed (or non - themed) bootstrap.css (or bootstrap.less) outside would be better? As bootstrap upgrades, the documentation site gets those updates for free?

I'd be happy to submit a PR of the core team is interested  :)

**Comment by buzzdecafe** [comment]
Thanks for the kind words, @gaurav21r . I think we'd all be happy to entertain a PR along these lines, thanks for the offer. The docs site is updated Blanche DuBois-style, i.e. it has "always depended on the kindness of strangers."

**Comment by craigdallimore** [comment]
Shall we close this when we  embed the standalone REPL? It [no longer](https://github.com/ramda/repl/pull/11) has Bootstrap in it.

(Presently working on making it embeddabizable :wink:  )

**Comment by MattMS** [comment]
Bootstrap variables (from the Node package) are being used throughout the [Less files](https://github.com/ramda/ramda.github.io/tree/master/less) so it may be difficult to separate them entirely.

I agree that it would be nice to separate out Bootstrap but this may be more work than it initially seems.

**Comment by gaurav21r** [comment]
@MattMS @craigdallimore @buzzdecafe I'm sorry I haven't been able to contribute so far. Actually we are researching best practices for Static Site Generators and API Style documentation over at https://github.com/rcorp/standard-project-structure

Our team hopes to close this by the end of the month and I can propose a more robust solution to the good folks here @ ramda!

My initial instinct is to make the Ramda documentation a **theme** based on the Static Site Generator research we'll do so that it can be more **centrally** maintained and Ramda gets free (effort wise) updates to its documentation structure.

If we make it completely feature / design compatible with the current site I am hoping Ramda team won't have a problem based on @buzzdecafe s response.
