### ISSUE TITLE
Mobile Menu Stuck open on IOS Safari and Glitch in Chrome between 750px and 770px

### ISSUE THREAD

**Issue by sstern6** [ramda/ramda.github.io#94]
Reading Rambda Docs on my iphone in safari and discovered on the home page menu is stuck open and glitches on desktop in chrome between 750px and 770px.  Would like to look into it further and submit a PR.  I have a feeling something is not being loaded or glitching on transition between desktop view and mobile.

Thank you

**Comment by buzzdecafe** [comment]
A PR would be most welcome, thank you

**Comment by sstern6** [comment]
Will look into it and create one when I have a solution, thank you

**Comment by sstern6** [comment]
@buzzdecafe looks like there is a transition for the mobile menu thats causing a hiccup on resizing that is eliminated when it is removed.  I was also considering on page load hiding the mobile menu just in case there is another bug causing the menu to be stuck open.  I cant replicate the mobile menu issue on the ios simulator but this is my hunch.  Thoughts?

**Comment by CrossEye** [comment]
I would love to know how reproducible this is.  Can other IOS users test this?

**Comment by sstern6** [comment]
@CrossEye Tested on a few other peers iphone 6's and cant seem to reproduce the issue except on my phone.  Will close the issue, thank you for your time
