### ISSUE TITLE
Make docs a todo list applicaiton

### ISSUE THREAD

**Issue by BLamy** [ramda/ramda.github.io#98]
Might seem kind of dumb but I keep my own separate spreadsheet where I mark off Ramda functions as I use them. It helps me track my progress, I really don't see any other way to learn a library like this. 

It would be nice If I in the docs I could check off functions that I'm familiar with and then filter the docs by used / unknown functions.

**Comment by CrossEye** [comment]
It doesn't seem as though there would be a huge call for something like this.  While I could be convinced, I would need to see more evidence that there are more people who would be interested in this.

**Comment by MattMS** [comment]
Maybe the concept could be implemented as a favourite/bookmark on functions?
Then others could use it as a quick reference tool.

For example, see "Add to Collection" star in the [Polymer docs](https://elements.polymer-project.org/elements/app-layout).

FWIW I'm not trying to push this either way as I haven't needed to use that feature yet.

**Comment by buzzdecafe** [comment]
closing without prejudice. should you decide to make a PR on this feature we'd certainly have a look
